site_name: Gavin's Garage

nav:
    - 🏡 Home: index.md
    - 🤵 About Gavin: about.md
    - 🧾 Projects:
      - 📝 NotePad: projects/pad/index.md
      - 📖 Book Summarization: projects/book-summarization/index.md
    - 🧠 Knowledge Base:
      - 📊 Item Analysis: knowledge/item-analysis.md

theme:
  logo: assets/favicon.png
  favicon: assets/favicon.png
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: deep purple
      accent: deep orange

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep purple
      accent: deep orange
    
plugins:
  - search
  
markdown_extensions:
  - footnotes

extra:
  generator: false
  